# Generated by Django 4.0.1 on 2022-02-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='preview',
            field=models.CharField(default='SOME STRING', max_length=140),
        ),
        migrations.AddField(
            model_name='task',
            name='text',
            field=models.TextField(default='default title', verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
    ]
