# Generated by Django 4.0.1 on 2022-02-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_task_task_task_preview_task_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('preview', models.CharField(max_length=140, verbose_name='Preview')),
                ('text', models.TextField(verbose_name='Main news')),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='preview',
            field=models.CharField(max_length=140),
        ),
    ]
