# Generated by Django 4.0.1 on 2022-02-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_news_alter_task_preview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='text',
            new_name='textNews',
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=80, verbose_name='Title'),
        ),
    ]
