# Generated by Django 4.0.1 on 2022-02-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_text_news_textnews_alter_news_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='textNews',
            field=models.CharField(max_length=10000, verbose_name='Main news'),
        ),
    ]
